PREFIX emobon-core: <https://data.emobon.embrc.eu/ns/core#>
PREFIX emobon-sampling: <https://data.emobon.embrc.eu/ns/sampling#>
PREFIX schema: <https://schema.org/>

CONSTRUCT {
    <./> schema:keywords ?biomeUri ;
         schema:keywords ?envMat ;
         schema:keywords ?taxId ;
         schema:keywords ?taxName ;
         schema:keywords <https://inspire.ec.europa.eu/metadata-codelist/TopicCategory/biota> .

    <https://inspire.ec.europa.eu/metadata-codelist/TopicCategory/biota> a schema:DefinedTerm ;
        schema:name "Biota" ;
        schema:identifier <https://inspire.ec.europa.eu/metadata-codelist/TopicCategory/biota> .
}
WHERE {
    {
        ?obs a emobon-core:Observatory .
        { ?obs emobon-core:broadBiome ?biomeUri }
        UNION
        { ?obs emobon-core:localBiome ?biomeUri }
    }
    UNION
    {
        ?sample a <http://www.w3.org/ns/sosa/Sample> .
        OPTIONAL { ?sample emobon-sampling:environmentMaterial ?envMat }
        OPTIONAL { ?sample emobon-sampling:taxonomicID ?taxId }
        OPTIONAL { ?sample emobon-sampling:taxonomicName ?taxName }
    }
}
