name: Update_latest_tag

on:
  push:
    branches:
      - main

jobs:

    update_latest_tag:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout
          uses: actions/checkout@v3
    
        - name: change latest tag
          uses: EndBug/latest-tag@latest
          env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             token: ${{ secrets.GITHUB_TOKEN }}
          with:
              # You can change the name of the tag or branch with this input.
              # Default: 'latest'
              ref: 'latest'
              # If a description is provided, the action will use it to create an annotated tag. If none is given, the action will create a lightweight tag.
              # Default: ''
              description: 'latest version of the observatory-profile.' 
              # Force-update a branch instead of using a tag.
              # Default: false
              force-branch: false