name: RO-Crate to Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: RO-Crate to Pages
        uses: vliz-be-opsci/rocrate-to-pages@latest
        with:
          config: config.yml
          space_to_pages_homepage: https://data.emobon.embrc.eu
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./unicornpages
