PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX schema: <http://schema.org/>

CONSTRUCT {
    <./> schema:measurementTechnique ?technique ;
         schema:instrument ?sampler .
}
WHERE {
    {
        ?obs a sosa:Observation ;
             schema:measurementTechnique ?technique .
    }
    UNION
    {
        ?sampling a sosa:Sampling ;
                  sosa:madeBySampler ?sampler .
    }
}
